# Generated by Django 6.0.1 on 2026-02-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_emprestimo', models.CharField(max_length=100)),
                ('livro_emprestado', models.CharField(max_length=100)),
                ('data_emprestimo', models.DateField()),
                ('data_devolucao', models.DateField()),
                ('tempo_duracao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('editora', models.CharField(max_length=100)),
                ('ano_publicacao', models.IntegerField()),
                ('isbn', models.CharField(max_length=13)),
                ('quantidade', models.IntegerField()),
                ('disponivel', models.BooleanField(default=True)),
                ('data_cadastro', models.DateField()),
                ('emprestado', models.BooleanField(default=False)),
                ('data_emprestimo', models.DateField()),
                ('data_devolucao', models.DateField()),
                ('nome_emprestimo', models.CharField(max_length=100)),
                ('tempo_duracao', models.DateField()),
            ],
            options={
                'verbose_name': 'Livro',
            },
        ),
    ]
