# Generated by Django 6.0.1 on 2026-02-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0003_alter_livros_tempo_duracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='co_autor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='livros',
            name='data_cadastro',
            field=models.DateField(auto_now=True),
        ),
    ]
