# Generated by Django 6.0.1 on 2026-02-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0004_livros_co_autor_alter_livros_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
