# Generated by Django 6.0.1 on 2026-02-01 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0007_livros_data_limite_devolucao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='data_limite_devolucao',
        ),
    ]
